# Generated by Django 4.2.5 on 2024-06-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_orders_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images/images')),
                ('desc', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
